In [32]:
# loading medical_cost
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
df = pd.read_csv("Medical cost.csv")
df

       age     sex     bmi  children smoker     region      charges
0     19.0  female  27.900       0.0    yes  southwest  16884.92400
1     18.0    male  33.770       1.0     no  southeast   1725.55230
2     28.0    male  33.000       3.0     no  southeast   4449.46200
3     33.0    male  22.705       0.0     no  northwest  21984.47061
4     32.0    male  28.880       0.0     no  northwest   3866.85520
...    ...     ...     ...       ...    ...        ...          ...
1333  50.0    male  30.970       3.0     no  northwest  10600.54830
1334  18.0  female  31.920       0.0     no  northeast   2205.98080
1335  18.0  female  36.850       0.0     no  southeast   1629.83350
1336  21.0  female  25.800       0.0     no  southwest   2007.94500
1337  61.0  female  29.070       0.0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [34]:
df.dtypes

age         float64
sex          object
bmi         float64
children    float64
smoker       object
region       object
charges     float64
dtype: object

In [35]:
df.age.unique()

array([19., 18., 28., 33., 32., 31., 46., 37., 60., 25., 62., 23., 56.,
       27., nan, 30., 34., 59., 63., 55., 35., 24., 41., 38., 36., 48.,
       40., 58., 53., 43., 64., 20., 61., 44., 57., 29., 21., 22., 45.,
       54., 26., 52., 49., 47., 51., 42., 50., 39.])

In [36]:
df['age'] = df['age'].fillna(df['age'].mean())
df['age'] = df['age'].astype(int)
df.dtypes

age           int64
sex          object
bmi         float64
children    float64
smoker       object
region       object
charges     float64
dtype: object

In [37]:
# encoder female avec labelencoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df

      age  sex     bmi  children smoker     region      charges
0      19    0  27.900       0.0    yes  southwest  16884.92400
1      18    1  33.770       1.0     no  southeast   1725.55230
2      28    1  33.000       3.0     no  southeast   4449.46200
3      33    1  22.705       0.0     no  northwest  21984.47061
4      32    1  28.880       0.0     no  northwest   3866.85520
...   ...  ...     ...       ...    ...        ...          ...
1333   50    1  30.970       3.0     no  northwest  10600.54830
1334   18    0  31.920       0.0     no  northeast   2205.98080
1335   18    0  36.850       0.0     no  southeast   1629.83350
1336   21    0  25.800       0.0     no  southwest   2007.94500
1337   61    0  29.070       0.0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [38]:
#label encoder sur smoker
df['smoker'] = le.fit_transform(df['smoker'])
df

      age  sex     bmi  children  smoker     region      charges
0      19    0  27.900       0.0       1  southwest  16884.92400
1      18    1  33.770       1.0       0  southeast   1725.55230
2      28    1  33.000       3.0       0  southeast   4449.46200
3      33    1  22.705       0.0       0  northwest  21984.47061
4      32    1  28.880       0.0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    1  30.970       3.0       0  northwest  10600.54830
1334   18    0  31.920       0.0       0  northeast   2205.98080
1335   18    0  36.850       0.0       0  southeast   1629.83350
1336   21    0  25.800       0.0       0  southwest   2007.94500
1337   61    0  29.070       0.0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [39]:
#frequency encoding sur region
# Calcul des fréquences
freq_region = df['region'].value_counts(normalize=True)

# Remplacement des catégories par leur fréquence
df['region_freq'] = df['region'].map(freq_region)

# (Optionnel) supprimer la colonne originale
df.drop(columns='region', inplace=True)

df.head()

   age  sex     bmi  children  smoker      charges  region_freq
0   19    0  27.900       0.0       1  16884.92400     0.242900
1   18    1  33.770       1.0       0   1725.55230     0.272048
2   28    1  33.000       3.0       0   4449.46200     0.272048
3   33    1  22.705       0.0       0  21984.47061     0.242900
4   32    1  28.880       0.0       0   3866.85520     0.242900

In [40]:
# gérer les valeurs manquantes
df.isna().sum()

age            0
sex            0
bmi            6
children       7
smoker         0
charges        0
region_freq    0
dtype: int64

In [41]:
# gérer les valeurs manquantes sur la colonne bmi et children
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())
df

      age  sex     bmi  children  smoker      charges  region_freq
0      19    0  27.900       0.0       1  16884.92400     0.242900
1      18    1  33.770       1.0       0   1725.55230     0.272048
2      28    1  33.000       3.0       0   4449.46200     0.272048
3      33    1  22.705       0.0       0  21984.47061     0.242900
4      32    1  28.880       0.0       0   3866.85520     0.242900
...   ...  ...     ...       ...     ...          ...          ...
1333   50    1  30.970       3.0       0  10600.54830     0.242900
1334   18    0  31.920       0.0       0   2205.98080     0.242152
1335   18    0  36.850       0.0       0   1629.83350     0.272048
1336   21    0  25.800       0.0       0   2007.94500     0.242900
1337   61    0  29.070       0.0       1  29141.36030     0.242900

[1338 rows x 7 columns]

In [42]:
# gérer les valeurs manquantes sur la colonne children
df['children'] = df['children'].fillna(df['children'].mean())
df

      age  sex     bmi  children  smoker      charges  region_freq
0      19    0  27.900       0.0       1  16884.92400     0.242900
1      18    1  33.770       1.0       0   1725.55230     0.272048
2      28    1  33.000       3.0       0   4449.46200     0.272048
3      33    1  22.705       0.0       0  21984.47061     0.242900
4      32    1  28.880       0.0       0   3866.85520     0.242900
...   ...  ...     ...       ...     ...          ...          ...
1333   50    1  30.970       3.0       0  10600.54830     0.242900
1334   18    0  31.920       0.0       0   2205.98080     0.242152
1335   18    0  36.850       0.0       0   1629.83350     0.272048
1336   21    0  25.800       0.0       0   2007.94500     0.242900
1337   61    0  29.070       0.0       1  29141.36030     0.242900

[1338 rows x 7 columns]

In [43]:
# séparer X et Y
X = df.drop('charges', axis=1)
y = df['charges']

In [44]:
# spliter X_train et x-test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [45]:
# standardisation de X_train X_test, Y-train et Y-test
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [49]:
X_train

array([[ 0.47271286, -1.0246016 , -1.75981531,  0.7396811 , -0.50874702,
        -0.57994927],
       [ 0.54419431, -1.0246016 , -1.03428248, -0.91171285, -0.50874702,
        -0.63756726],
       [ 0.90160158, -1.0246016 , -0.94462854, -0.91171285, -0.50874702,
         1.66715223],
       ...,
       [ 1.33049029,  0.97598911, -0.89233041, -0.91171285, -0.50874702,
        -0.63756726],
       [-0.17062022, -1.0246016 ,  2.83079859,  0.7396811 ,  1.96561348,
        -0.57994927],
       [ 1.11604593,  0.97598911, -0.10785841, -0.91171285, -0.50874702,
        -0.57994927]])

In [50]:
# importer les librairies pour tensoflow
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [51]:
# Build model
model = Sequential()
model.add(Dense(10, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(10, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [52]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │            70 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 301 (1.18 KB)

 Trainable params: 301 (1.18 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mean_squared_error'])

In [ ]:
ann = model.fit(X_train, y_train, epochs=100, validation_split=0.2, batch_size=16, verbose=1)
# verbose pour dire affiche les textes

Epoch 1/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.9995 - mean_squared_error: 0.9995 - val_loss: 0.9120 - val_mean_squared_error: 0.9120
Epoch 2/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8218 - mean_squared_error: 0.8218 - val_loss: 0.6619 - val_mean_squared_error: 0.6619
Epoch 3/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5440 - mean_squared_error: 0.5440 - val_loss: 0.4042 - val_mean_squared_error: 0.4042
Epoch 4/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3806 - mean_squared_error: 0.3806 - val_loss: 0.2826 - val_mean_squared_error: 0.2826
Epoch 5/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2702 - mean_squared_error: 0.2702 - val_loss: 0.2338 - val_mean_squared_error: 0.2338
Epoch 6/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2314 - mean_squared_error: 0.2314 - val_loss: 0.1981 - val_mean_squared_error: 0.1981
Epoch 7/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2157 - mean_squared_error: 0.2157 - val_loss: 0.1785 - val_mean_squared_error: 0.1785
Epoch 8/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1823 - mean_squared_error: 0.1823 - val_loss: 0.1733 - val_mean_squared_error: 0.1733
Epoch 9/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1656 - mean_squared_error: 0.1656 - val_loss: 0.1673 - val_mean_squared_error: 0.1673
Epoch 10/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1890 - mean_squared_error: 0.1890 - val_loss: 0.1646 - val_mean_squared_error: 0.1646
Epoch 11/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1946 - mean_squared_error: 0.1946 - val_loss: 0.1658 - val_mean_squared_error: 0.1658
Epoch 12/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1905 - mean_squared_error: 0.1905 - val_loss: 0.1612 - val_mean_squared_error: 0.1612
Epoch 13/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.1827 - mean_squared_error: 0.1827 - val_loss: 0.1576 - val_mean_squared_error: 0.1576
Epoch 14/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1997 - mean_squared_error: 0.1997 - val_loss: 0.1602 - val_mean_squared_error: 0.1602
Epoch 15/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1421 - mean_squared_error: 0.1421 - val_loss: 0.1567 - val_mean_squared_error: 0.1567
Epoch 16/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1783 - mean_squared_error: 0.1783 - val_loss: 0.1599 - val_mean_squared_error: 0.1599
Epoch 17/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1653 - mean_squared_error: 0.1653 - val_loss: 0.1547 - val_mean_squared_error: 0.1547
Epoch 18/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1736 - mean_squared_error: 0.1736 - val_loss: 0.1548 - val_mean_squared_error: 0.1548
Epoch 19/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.1553 - mean_squared_error: 0.1553 - val_loss: 0.1574 - val_mean_squared_error: 0.1574
Epoch 20/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.1669 - mean_squared_error: 0.1669 - val_loss: 0.1536 - val_mean_squared_error: 0.1536
Epoch 21/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.1280 - mean_squared_error: 0.1280 - val_loss: 0.1527 - val_mean_squared_error: 0.1527
Epoch 22/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1685 - mean_squared_error: 0.1685 - val_loss: 0.1473 - val_mean_squared_error: 0.1473
Epoch 23/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1589 - mean_squared_error: 0.1589 - val_loss: 0.1485 - val_mean_squared_error: 0.1485
Epoch 24/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1482 - mean_squared_error: 0.1482 - val_loss: 0.1494 - val_mean_squared_error: 0.1494
Epoch 25/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1614 - mean_squared_error: 0.1614 - val_loss: 0.1514 - val_mean_squared_error: 0.1514
Epoch 26/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.1525 - mean_squared_error: 0.1525 - val_loss: 0.1525 - val_mean_squared_error: 0.1525
Epoch 27/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.1566 - mean_squared_error: 0.1566 - val_loss: 0.1456 - val_mean_squared_error: 0.1456
Epoch 28/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1389 - mean_squared_error: 0.1389 - val_loss: 0.1484 - val_mean_squared_error: 0.1484
Epoch 29/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1562 - mean_squared_error: 0.1562 - val_loss: 0.1512 - val_mean_squared_error: 0.1512
Epoch 30/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1425 - mean_squared_error: 0.1425 - val_loss: 0.1446 - val_mean_squared_error: 0.1446
Epoch 31/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1481 - mean_squared_error: 0.1481 - val_loss: 0.1446 - val_mean_squared_error: 0.1446
Epoch 32/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1602 - mean_squared_error: 0.1602 - val_loss: 0.1440 - val_mean_squared_error: 0.1440
Epoch 33/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1685 - mean_squared_error: 0.1685 - val_loss: 0.1440 - val_mean_squared_error: 0.1440
Epoch 34/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1306 - mean_squared_error: 0.1306 - val_loss: 0.1456 - val_mean_squared_error: 0.1456
Epoch 35/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1589 - mean_squared_error: 0.1589 - val_loss: 0.1434 - val_mean_squared_error: 0.1434
Epoch 36/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1378 - mean_squared_error: 0.1378 - val_loss: 0.1419 - val_mean_squared_error: 0.1419
Epoch 37/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1738 - mean_squared_error: 0.1738 - val_loss: 0.1441 - val_mean_squared_error: 0.1441
Epoch 38/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1464 - mean_squared_error: 0.1464 - val_loss: 0.1450 - val_mean_squared_error: 0.1450
Epoch 39/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1634 - mean_squared_error: 0.1634 - val_loss: 0.1412 - val_mean_squared_error: 0.1412
Epoch 40/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1461 - mean_squared_error: 0.1461 - val_loss: 0.1446 - val_mean_squared_error: 0.1446
Epoch 41/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.1364 - mean_squared_error: 0.1364 - val_loss: 0.1425 - val_mean_squared_error: 0.1425
Epoch 42/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1473 - mean_squared_error: 0.1473 - val_loss: 0.1448 - val_mean_squared_error: 0.1448
Epoch 43/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.1554 - mean_squared_error: 0.1554 - val_loss: 0.1469 - val_mean_squared_error: 0.1469
Epoch 44/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.1569 - mean_squared_error: 0.1569 - val_loss: 0.1433 - val_mean_squared_error: 0.1433
Epoch 45/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.1316 - mean_squared_error: 0.1316 - val_loss: 0.1444 - val_mean_squared_error: 0.1444
Epoch 46/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.1310 - mean_squared_error: 0.1310 - val_loss: 0.1433 - val_mean_squared_error: 0.1433
Epoch 47/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.1385 - mean_squared_error: 0.1385 - val_loss: 0.1453 - val_mean_squared_error: 0.1453
Epoch 48/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1733 - mean_squared_error: 0.1733 - val_loss: 0.1528 - val_mean_squared_error: 0.1528
Epoch 49/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1257 - mean_squared_error: 0.1257 - val_loss: 0.1516 - val_mean_squared_error: 0.1516
Epoch 50/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1614 - mean_squared_error: 0.1614 - val_loss: 0.1533 - val_mean_squared_error: 0.1533
Epoch 51/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1161 - mean_squared_error: 0.1161 - val_loss: 0.1435 - val_mean_squared_error: 0.1435
Epoch 52/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1430 - mean_squared_error: 0.1430 - val_loss: 0.1453 - val_mean_squared_error: 0.1453
Epoch 53/100
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.1477 - mean_squared_error: 0.1477 - val_loss: 0.1499 - val_mean_squared_error: 0.1499
Epoch 54/100